#!/bin/bash

chefvm()
{
  if [ -z $1 ]; then
    echo "USAGE: chefvm use CONFIG"
  fi

  __chefvm_use $1
}

__chefvm_use()
{
  configurations="configurations"
  config=$1
  config_path="$configurations/$config"

  if [ "$chefvm_current_config" != "$config" ]; then
    if [ ! -z $chefvm_current_config ]; then
      for i in $(ls "$configurations/$chefvm_current_config")
      do
        rm -f $i
      done
    fi

    for file in $(ls $config_path)
    do
      ln -s $config_path/$file $file
    done

    echo "Using chef config \"$config\""
    export chefvm_current_config="$config"
  fi
}
