#!/usr/bin/env bash
# Usage: chefvm export CONFIG
# Summary: Export a configuration
# Help: This command will export a configuration to a file so it can be imported on another machine.

set -e

__chefvm_config $1

if [ -z "$config" ]; then
  echo "No name provided"
  exit 1
fi

if [ ! -d $_CHEFVM_ROOT/$config_path ]; then
  echo "No configuration named $1 found."
  chefvm list
  exit 1
fi

echo "Exporting: $config"
pushd $_CHEFVM_ROOT > /dev/null
tar czf $_CHEFVM_ROOT/exports/${config}.tar.gz $config_path
popd > /dev/null
