#!/usr/bin/env bash
set -e

print=""
if [ "$1" = "-" ]; then
  print=1
  shift
fi
shell="$1"
if [ -z "$shell" ]; then
  shell="$(ps c -p "$PPID" -o 'ucomm=' 2>/dev/null || true)"
  shell="${shell##-}"
  shell="${shell%% *}"
  shell="$(basename "${shell:-$SHELL}")"
fi

resolve_link() {
  $(type -p greadlink readlink | head -1) $1
}

abs_dirname() {
  local cwd="$(pwd)"
  local path="$1"

  while [ -n "$path" ]; do
    cd "${path%/*}"
    local name="${path##*/}"
    path="$(resolve_link "$name" || true)"
  done

  pwd
  cd "$cwd"
}

root="$(abs_dirname "$0")/.."

if [ -z "$print" ]; then
  case "$shell" in
  bash )
    profile='~/.bash_profile'
    ;;
  zsh )
    profile='~/.zshenv'
    ;;
  * )
    profile='your profile'
    ;;
  esac

  { echo "# Load chefvm automatically by adding"
    echo "# the following to ${profile}:"
    echo
    echo "eval \"\$(${_CHEFVM_ROOT}/bin/chefvm init -)\""
    echo
  } >&2

  exit 1
fi

bin_path="${_CHEFVM_ROOT}/bin"
case "$shell" in
fish )
  echo "eval 'set -x PATH \$PATH \"$bin_path\"';"
  ;;
* )
  echo "export PATH=\"\$PATH:$bin_path\""
  ;;
esac

case "$shell" in
bash | zsh )
  echo "source \"$root/completions/chefvm.${shell}\""
  ;;
esac

commands=(`chefvm commands --sh`)
IFS="|"
case "$shell" in
fish )
  cat <<EOS
  eval '
function chefvm
  set command "\$1"
  if test [ "\$argv" -gt 0 ]
    shift
  end

  switch "\$command"
    case ${commands[*]}
      eval \`chefvm "sh-\$command" "\$argv"\`
    case "*"
      command chefvm "\$command" "\$argv";
  end
end';
eval 'chefvm setup';
EOS
  ;;
* )
  cat <<EOS
chefvm() {
  local command="\$1"
  if [ "\$#" -gt 0 ]; then
    shift
  fi

  case "\$command" in
  ${commands[*]})
    eval \`chefvm "sh-\$command" "\$@"\`;;
  *)
    command chefvm "\$command" "\$@";;
  esac
}
chefvm setup
EOS
  ;;
esac
