#!/usr/bin/env bash
# Usage: chefvm update
# Summary: This will update chefvm to the latest using git
# Help: This command makes it easy to update chefvm to the latest version from trobrock/chefvm@master

set -e

__chefvm_config $1

cd $_CHEFVM_ROOT
git fetch origin
tag="$( git describe --tags --abbrev=0 `git rev-list --tags --max-count=1` )"
diff="$( git cherry -v HEAD $tag | wc -l )"

if [ "$diff" -eq 0 ]; then
  echo "Already up to date."
else
  echo "Update to version: $tag? (Y/n)"
  read cont

  if [ ! "$cont" == "n" ]; then
    git reset --hard $tag
    echo "Updated to $tag!"
  else
    echo "Not updating right now."
  fi
fi
