#!/usr/bin/env bash
# Usage: chefvm copy CONFIG NEW_CONFIG
# Summary: This will copy one chef configuration to a new name
# Help: This command allows you to clone one configuration to a new name

set -e

__chefvm_config $1

if [ -z "$config" ]; then
  echo "No name provided"
  exit 1
fi

if [ ! -d $_CHEFVM_ROOT/$config_path ]; then
  echo "No configuration named $1 found."
  chefvm list
  exit 1
fi

if [ -z "$2" ]; then
  echo "No destination name provided"
  exit 1
fi

echo "Copying: $config to $2" 
cp -R $_CHEFVM_ROOT/$config_path $_CHEFVM_ROOT/$configurations/$2
