#!/usr/bin/env bash

chefvm()
{
  command=$1
  config=$2
  [[ -z "$command" ]] && command="list"

  case "$command" in
    "use")
      __chefvm_use $config
      ;;
    "default")
      __chefvm_default $config
      ;;
    "create")
      __chefvm_create $config
      ;;
    "edit")
      __chefvm_edit $config
      ;;
    "list")
      __chefvm_list
      ;;
    "delete")
      __chefvm_delete $config
      ;;
    *)
      __chefvm_use $command
      ;;
  esac
}

__chefvm_use()
{
  __chefvm_config $1

  if [[ "$1" == "default" ]] && [ ! -d "$root_dir/$config_path" ]; then
    echo "No default config set"
    return 1
  elif [ ! -d "$root_dir/$config_path" ]; then
    echo "Now configuration with that name was found"
    return 2
  fi

  rm -f $current_path
  ln -s $config_path $current_path

  echo "Using chef config \"$config\""
}

__chefvm_default()
{
  if [ -z "$1" ]; then
    __chefvm_use "default"
    return
  fi

  __chefvm_config $1

  rm -f $default_path
  ln -s $config $default_path

  echo "Default chef configuration set to: $config"
}

__chefvm_create()
{
  if [ -z "$1" ]; then
    echo "No name provided"
    return 1
  fi

  __chefvm_config $1

  mkdir -p $root_dir/$config_path

  echo "Creating configuration: $config"
  __chefvm_use $config
  echo "Copy your pem file to ~/.chef and run 'knife configure'"
}

__chefvm_delete()
{
  if [ -z "$1" ]; then
    echo "No name provided"
    return 1
  fi

  __chefvm_config $1

  default_config=$(readlink $default_path)
  if [[ "$default_config" == "$config" ]]; then
    rm $default_path
  fi

  current_config=$(readlink $current_path | sed "s/$configurations\///")
  if [[ "$current_config" == "$config" ]]; then
    rm $current_path
  fi

  rm -rf $root_dir/$config_path

  echo "Removed $config"
}

__chefvm_edit() 
{
  if [ -z "$1" ]; then
    echo "No name provided"
    return 1
  fi

  if [ -z "$EDITOR" ]; then
    echo "You must set \$EDITOR"
    return 1
  fi

  __chefvm_config $1

  $EDITOR $root_dir/$config_path
}

__chefvm_list()
{
  __chefvm_config

  default_config=$(readlink $default_path)
  for c in $(ls $root_dir/$configurations)
  do
    opts="  "
    if [[ "$c" == "$config" && "$c" == "$default_config" ]]; then
      opts="*="
    elif [[ "$c" == "$config" ]]; then
      opts="=>"
    elif [[ "$c" == "$default_config" ]]; then
      opts="* "
    fi

    [[ "$c" != "default" ]] && echo "$opts $c"
  done

  echo
  echo "=> - current"
  echo "=* - current and default"
  echo "*  - default"
}

__chefvm_config()
{
  root_dir="$HOME/.chefvm"
  configurations="configurations"
  current_path="$root_dir/current"

  config=$1
  if [[ -z "$config" ]]; then
    config=$(readlink $current_path | sed "s/$configurations\///")
  fi

  default_path="$root_dir/$configurations/default"
  config_path="$configurations/$config"

  if [[ "$config" == "default" ]]; then
    config=$(readlink $default_path)
  fi
}

__chefvm_setup()
{
  __chefvm_config
  [[ ! -e "$HOME/.chef" ]] && ln -s $current_path $HOME/.chef

  config=$(readlink $current_path | sed "s/$configurations\///")
  [[ -z "$config" ]] && __chefvm_use default > /dev/null
}

__chefvm_setup
